// Comprehensive list of Kenyan locations for autocomplete
export const KENYA_LOCATIONS: string[] = [
  // Major Cities
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Eldoret",
  "Thika",
  "Malindi",
  "Kitale",
  "Garissa",
  "Nyeri",
  "Kakamega",
  "Machakos",
  "Meru",
  "Kisii",
  "Embu",
  "Kilifi",
  "Lamu",
  "Lodwar",
  "Mandera",
  "Wajir",
  "Isiolo",
  "Nanyuki",
  "Kericho",
  "Bomet",
  "Narok",
  "Migori",
  "Homa Bay",
  "Siaya",
  "Bungoma",
  "Busia",
  "Voi",
  "Taveta",
  "Maralal",
  "Moyale",
  "Marsabit",
  "Iten",
  "Kapenguria",
  "Kabarnet",
  "Kajiado",
  "Ngong",

  // Nairobi Neighborhoods & Sub-locations
  "Nairobi CBD",
  "Westlands",
  "Kilimani",
  "Karen",
  "Langata",
  "Eastleigh",
  "Kasarani",
  "Embakasi",
  "Roysambu",
  "Ruaka",
  "Kiambu",
  "Runda",
  "Lavington",
  "Spring Valley",
  "Gigiri",
  "Muthaiga",
  "Parklands",
  "Highridge",
  "Pangani",
  "Mathare",
  "Huruma",
  "Dandora",
  "Korogocho",
  "Kayole",
  "Umoja",
  "Utawala",
  "Ruai",
  "Githurai",
  "Zimmerman",
  "Kahawa",
  "Kahawa West",
  "Kahawa Sukari",
  "Ruiru",
  "Juja",
  "Mwihoko",
  "Ngara",
  "Milimani",
  "South C",
  "South B",
  "Donholm",
  "Buruburu",
  "Makadara",
  "Pumwani",
  "Bahati",
  "Hamza",
  "Imara Daima",
  "Athi River",
  "Kitengela",
  "Mlolongo",
  "Syokimau",
  "Mavoko",
  "Rongai",
  "Galleria",
  "Hardy",
  "Riara",
  "Dagoretti",
  "Kawangware",
  "Kangemi",
  "Uthiru",
  "Kikuyu",
  "Limuru",
  "Tigoni",
  "Kinoo",
  "Kabete",
  "Wangige",
  "Loresho",
  "Ridgeways",
  "Mountain View",
  "Highrise",
  "Upper Hill",
  "Hospital Hill",
  "Hurlingham",
  "Adams Arcade",
  "Yaya",
  "Valley Arcade",
  "Lenana",
  "Kilimani East",
  "Lower Kabete",
  "Chiromo",

  // Mombasa Areas
  "Mombasa Island",
  "Mombasa CBD",
  "Nyali",
  "Bamburi",
  "Shanzu",
  "Kisauni",
  "Likoni",
  "Changamwe",
  "Miritini",
  "Port Reitz",
  "Tudor",
  "Mvita",
  "Ganjoni",
  "Majengo",
  "Old Town Mombasa",
  "Diani",
  "Ukunda",
  "Kinango",
  "Kwale",
  "Msambweni",

  // Kisumu Areas
  "Kisumu CBD",
  "Milimani Kisumu",
  "Nyalenda",
  "Manyatta",
  "Kondele",
  "Mamboleo",
  "Riat",
  "Kisian",
  "Ahero",
  "Maseno",
  "Winam",

  // Nakuru Areas
  "Nakuru CBD",
  "Milimani Nakuru",
  "Lanet",
  "Barnabas",
  "Shauri Yako",
  "London",
  "Kaptembwo",
  "Flamingo",
  "Lake View",
  "Bahati",
  "Subukia",
  "Gilgil",
  "Naivasha",
  "Molo",
  "Njoro",

  // Eldoret Areas
  "Eldoret CBD",
  "Huruma Eldoret",
  "Langas",
  "Kapseret",
  "Ngeria",
  "Pioneer",
  "Munyaka",
  "Elgon View",
  "Bondeni",
  "Annex",
  "Zonal",
  "Turbo",
  "Burnt Forest",
  "Moiben",

  // Other Key Towns
  "Thika CBD",
  "Makongeni",
  "Garissa Lodge",
  "Nyeri CBD",
  "Karatina",
  "Kerugoya",
  "Kutus",
  "Sagana",
  "Muranga",
  "Maragua",
  "Kiria-ini",
  "Kangema",
  "Gatundu",
  "Githunguri",
  "Karuri",
  "Kijabe",
  "Naivasha CBD",
  "Gilgil CBD",
  "Maai Mahiu",
  "Longonot",
  "Suswa",
  "Maji Mazuri",
  "Nkubu",
  "Meru CBD",
  "Timau",
  "Maua",
  "Githongo",
  "Chuka",
  "Tharaka",
  "Embu CBD",
  "Runyenjes",
  "Siakago",
  "Kibera",
  "Dagoretti Corner",
  "Kikuyu Junction",
  "Machakos CBD",
  "Matuu",
  "Kangundo",
  "Tala",
  "Masinga",
  "Kitui",
  "Mwingi",
  "Migwani",
  "Mutomo",
  "Kilifi CBD",
  "Mtwapa",
  "Mariakani",
  "Kaloleni",
  "Malindi CBD",
  "Watamu",
  "Gede",
  "Lamu Island",
  "Mpeketoni",
  "Hola",
  "Kericho CBD",
  "Litein",
  "Londiani",
  "Fort Ternan",
  "Bomet CBD",
  "Sotik",
  "Mulot",
  "Narok CBD",
  "Olekejuado",
  "Kisii CBD",
  "Ogembo",
  "Keroka",
  "Rongo",
  "Migori CBD",
  "Uriri",
  "Homa Bay CBD",
  "Oyugis",
  "Ndhiwa",
  "Siaya CBD",
  "Bondo",
  "Ugunja",
  "Kakamega CBD",
  "Mumias",
  "Malava",
  "Butere",
  "Shinyalu",
  "Bungoma CBD",
  "Webuye",
  "Kimilili",
  "Chwele",
  "Busia CBD",
  "Malaba",
  "Nambale",
  "Kitale CBD",
  "Endebess",
  "Kapenguria CBD",
  "Sigor",
  "Kabarnet CBD",
  "Mogotio",
  "Iten CBD",
  "Tambach",
  "Kapcherop",
  "Lodwar CBD",
  "Kalokol",
  "Kakuma",
  "Maralal CBD",
  "Baragoi",
  "Isiolo CBD",
  "Merti",
  "Marsabit CBD",
  "Moyale CBD",
  "Mandera CBD",
  "Wajir CBD",
  "Garissa CBD",
  "Dadaab",
  "Tarbaj",
];

export function searchLocations(query: string, limit = 10): string[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const results = KENYA_LOCATIONS.filter((loc) => loc.toLowerCase().includes(q));
  // Sort: exact start first, then contains
  results.sort((a, b) => {
    const aStart = a.toLowerCase().startsWith(q);
    const bStart = b.toLowerCase().startsWith(q);
    if (aStart && !bStart) return -1;
    if (!aStart && bStart) return 1;
    return a.localeCompare(b);
  });
  return results.slice(0, limit);
}
